package de.handler.mobile.android.bachelorapp.app.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.handler.mobile.android.bachelorapp.app.database.Guerrilla;
import de.handler.mobile.android.bachelorapp.app.database.MediaType;
import de.handler.mobile.android.bachelorapp.app.database.Media;
import de.handler.mobile.android.bachelorapp.app.database.GuerrillaProse;

import de.handler.mobile.android.bachelorapp.app.database.GuerrillaDao;
import de.handler.mobile.android.bachelorapp.app.database.MediaTypeDao;
import de.handler.mobile.android.bachelorapp.app.database.MediaDao;
import de.handler.mobile.android.bachelorapp.app.database.GuerrillaProseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig guerrillaDaoConfig;
    private final DaoConfig mediaTypeDaoConfig;
    private final DaoConfig mediaDaoConfig;
    private final DaoConfig guerrillaProseDaoConfig;

    private final GuerrillaDao guerrillaDao;
    private final MediaTypeDao mediaTypeDao;
    private final MediaDao mediaDao;
    private final GuerrillaProseDao guerrillaProseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        guerrillaDaoConfig = daoConfigMap.get(GuerrillaDao.class).clone();
        guerrillaDaoConfig.initIdentityScope(type);

        mediaTypeDaoConfig = daoConfigMap.get(MediaTypeDao.class).clone();
        mediaTypeDaoConfig.initIdentityScope(type);

        mediaDaoConfig = daoConfigMap.get(MediaDao.class).clone();
        mediaDaoConfig.initIdentityScope(type);

        guerrillaProseDaoConfig = daoConfigMap.get(GuerrillaProseDao.class).clone();
        guerrillaProseDaoConfig.initIdentityScope(type);

        guerrillaDao = new GuerrillaDao(guerrillaDaoConfig, this);
        mediaTypeDao = new MediaTypeDao(mediaTypeDaoConfig, this);
        mediaDao = new MediaDao(mediaDaoConfig, this);
        guerrillaProseDao = new GuerrillaProseDao(guerrillaProseDaoConfig, this);

        registerDao(Guerrilla.class, guerrillaDao);
        registerDao(MediaType.class, mediaTypeDao);
        registerDao(Media.class, mediaDao);
        registerDao(GuerrillaProse.class, guerrillaProseDao);
    }
    
    public void clear() {
        guerrillaDaoConfig.getIdentityScope().clear();
        mediaTypeDaoConfig.getIdentityScope().clear();
        mediaDaoConfig.getIdentityScope().clear();
        guerrillaProseDaoConfig.getIdentityScope().clear();
    }

    public GuerrillaDao getGuerrillaDao() {
        return guerrillaDao;
    }

    public MediaTypeDao getMediaTypeDao() {
        return mediaTypeDao;
    }

    public MediaDao getMediaDao() {
        return mediaDao;
    }

    public GuerrillaProseDao getGuerrillaProseDao() {
        return guerrillaProseDao;
    }

}
